name: ${APP_NAME}

services:
  app:
    build: .
    container_name: ${APP_NAME}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
